### ISSUE TITLE
Centered Point

### ISSUE THREAD

**Issue by l1keafox** [l1keafox/reMiddleWhere#26]
As a GROUP, I want to know the center point, so That I can meet with others.
- [x] It is DONE when lat/long in the Group is updated.

As a GROUP, I want to know the average center point in a group of users.
- [x] It is DONE when lat/long is calculated from the locations Array.

As a USER, When I get the GROUP data, I should get a updated center point.
- [x] It is DONE when a user asked for information, it should be updated.

**Comment by alverson98** [comment]
Notes to complete above tasks - 

1. Query for all of the users' locations, calculate the new center lat/long, mutation to update group center 
2. Confirm calculations are working properly with seeded data & manipulate the data - pass the correct data to the calc function
3. Mutation to update location for user & add location to group, then ties into steps for #1 to update group center
